### ISSUE TITLE
ExampleForce class is not preserved when added to System

### ISSUE THREAD

**Issue by zonca** [peastman/openmmexampleplugin#10]
I noticed that when I use `System.addForce` to add `ExampleForce` to a system, its class is not preserved, but the object is cast to the base class `Force`.

However this does not happen with other forces, for example the AMOEBA classes.

See a minimal example here:
http://nbviewer.ipython.org/gist/zonca/317fcf45c695ca4972a9

This makes it impossible to access the class specific methods. Do you know how to get around this issue? Thanks!

**Comment by zonca** [comment]
I am still affected by this issue, I think it is an issue with `swig` but I don't know how to fix it.

See a better minimal example here:

http://nbviewer.ipython.org/gist/zonca/d12528cf2c96b80ff152

**Comment by peastman** [comment]
Unfortunately, I don't have a good solution for this.  The way SWIG works, you need to provide a list of every possible Force subclass *at the time getForce() is generated*.  It then has hardcoded logic for casting to each of those.  In terms of the actual code, this is done at https://github.com/pandegroup/openmm/blob/master/wrappers/python/src/swig_doxygen/swigInputBuilder.py#L192-L227.  But for a plugin that gets compiled independently, that obviously doesn't work.

**Comment by zonca** [comment]
ok, thanks @peastman , it looks like there is no way to fix this for now.
