### ISSUE TITLE
Windows support - DLL not found

### ISSUE THREAD

**Issue by mikeoconnor0308** [peastman/openmmexampleplugin#16]
What steps are necessary to get this example plugin working on Windows, wrapped with python? 

I've finally gotten around to writing an [OpenMM plugin](https://gitlab.com/intangiblerealities/narupaplugins/openmm-vmd-imd) for interactive visualization & simulation. It would be nice if it worked on Windows, for dev with VR! However, I can't seem to get it the example plugin to work on Windows.

Steps taken: 

- Fresh conda environment with OpenMM installed (see attached [conda_environment.yml.txt](https://github.com/peastman/openmmexampleplugin/files/3973149/conda_environment.yml.txt)) 
- Set up cmake (see attached [CMakeCache.txt](https://github.com/peastman/openmmexampleplugin/files/3973141/CMakeCache.txt)):
    *  Skip OpenCL and CUDA - we're missing pthreads, but that's ok for now. 
    *  Generator: Visual Studio 15 2017 x64 bit 
- build, install, python install, output from that looks like it's all installed fine (see attached [build.log](https://github.com/peastman/openmmexampleplugin/files/3973142/build.log))

Attempt import:

```
>>> import exampleplugin
  File "<stdin>", line 1, in <module>
  File "[....]\lib\site-packages\exampleplugin.py", line 15, in <module>
    import _exampleplugin
ImportError: DLL load failed: The specified module could not be found.
```

I've run dependency walker on `ExamplePlugin.dll` and it all looks ok, so not sure what's causing the problem.

**Comment by peastman** [comment]
Most likely this is a library linking issue.  Do you have the OpenMM `lib` directory in your `PATH`?

**Comment by mikeoconnor0308** [comment]
Yep, you were right about a linking issue - the lib paths were not set. I expected the conda environment to handle this for me, is that not the case on Windows?

I now have a second problem (happy to move to new issue if desired), which is that the example plugin fails to initialize a DLL:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mike\Anaconda3\envs\omm-plugin\lib\site-packages\exampleplugin.py", line 15, in <module>
    import _exampleplugin
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.
```

 Narrowing it down a bit, it fails to register the serialisation proxy: 

```
Exception thrown at 0x00007FF87FEE9159 in TestSerializeExampleForce.exe: Microsoft C++ exception: std::bad_alloc at memory location 0x000000D5D26FE910.
```
This is occurring at [line 41 of ExampleForceProxy.cpp](https://github.com/peastman/openmmexampleplugin/blob/5c24825512d683d275d131dcd4f4d0a711e1b9ad/serialization/src/ExampleForceProxy.cpp#L41), presumably in `SerializationProxy("ExampleForce")`

I'm unable to get any more information without compiling OpenMM with debug symbols, do you have any ideas?

**Comment by peastman** [comment]
See if you can identify exactly where the error is occurring.  You should be able to do it by instrumenting the plugin code.  Add `printf()` calls at various points to see what code gets reached before it fails.  Hopefully you can quickly narrow it down to the exact line.

**Comment by mikeoconnor0308** [comment]
It's raising the exception at line 41 of ExampleForceProxy.cpp (verified through printing and debugging), specifically at the `SerializationProxy("ExampleForce")` constructor (see call stack below). 

Since we can't build OpenMM on Windows in 64-bit with debugging symbols, I built OpenMM and the plugin in 32-bit to see if I could shed light with more detailed debugging. Curiously, that **works perfectly**.

So the problem appears to be specific to 64-bit builds, as a clean 64-bit build of OpenMM, with Visual Studio 15 2017, with the Example Plugin built analogously, produces the error.

What Visual Studio C++ compiler do you use for building and testing OpenMM and plugins? 

Call stack: 
```
 	KernelBase.dll!00007ff87fee9159()	Unknown
 	vcruntime140.dll!00007ff86cd9486d()	Unknown
 	OpenMM.dll!00007ff8272a3003()	Unknown
 	OpenMM.dll!00007ff8272a1f81()	Unknown
 	OpenMM.dll!00007ff82714d301()	Unknown
 	OpenMM.dll!00007ff82726c6e3()	Unknown
>	ExamplePlugin.dll!OpenMM::ExampleForceProxy::ExampleForceProxy() Line 41	C++
 	ExamplePlugin.dll!registerExampleSerializationProxies() Line 63	C++
 	ExamplePlugin.dll!DllMain(void * hModule, unsigned long ul_reason_for_call, void * lpReserved) Line 52	C++
 	[External Code]	
```

**Comment by peastman** [comment]
So the error is happening somewhere inside the superclass constructor.  But the superclass constructor doesn't do anything except record the string you pass it.  This definitely seems like a library incompatibility of some sort.

Just to be clear, you compiled OpenMM yourself, right?  And you compiled it and the plugin with the same compiler and identical settings?  And if you compile them both in 32 bit mode everything works, but if you compile them both in 64 bit mode you get the error?

**Comment by mikeoconnor0308** [comment]
You were correct - I'm not sure what was dirtying the system but it's working fine now!
